- name: Add SSH key for passwordless login
  authorized_key:
    user: pi
    key: '{{ item }}'
  with_file:
    - '{{ ssh_public_key_path }}'

- name: Change default password
  user:
    name: pi
    password: '{{ user_password }}'

- name: Update apt package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install git
  package:
    name: git
    state: present

- name: Update apt packages
  apt:
    upgrade: safe
