- name: Makes a Raspberry Pi ready to run Node.js apps.
  hosts: pi
  remote_user: pi
  become: yes
  vars_files:
    - ./vars/auth.yml
    - ./vars/base.yml
  roles:
    - basics
    - geerlingguy.security
    - geerlingguy.ntp
    - nodesource.node
    - node
