- name: Sets up user accounts and applies basic updates & hardening.
  hosts: pi
  remote_user: pi
  become: yes
  vars_files:
    - ./vars/auth.yml
    - ./vars/base.yml
  roles:
    - basics
    - geerlingguy.security
    - geerlingguy.ntp
