- name: Remove example site config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Write nginx config
  template:
    src: ../templates/default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - restart nginx

- name: Set up certbot
  include_tasks: certbot.yml
