# geerlingguy.firewall - see https://galaxy.ansible.com/geerlingguy/firewall

firewall_allowed_tcp_ports:
  - '22' # ssh
  - '80' # http
  - '443' # https
firewall_allowed_udp_ports:
  - '5353' # avahi - required to use raspberrypi.local address

firewall_forwarded_tcp_ports: []
firewall_forwarded_udp_ports: []

# geerlingguy.security - see https://galaxy.ansible.com/geerlingguy/security

security_ssh_port: 22
security_sudoers_passwordless:
  - pi

# geerlingguy.ntp - see https://galaxy.ansible.com/geerlingguy/ntp

ntp_timezone: Europe/London
