# See https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

- name: Create global package directory
  file:
    path: /home/worker/.npm-packages
    owner: worker
    group: worker
    state: directory

- name: Add global package directory to .npmrc
  copy:
    dest: /home/worker/.npmrc
    content: 'prefix=${HOME}/.npm-packages'
    owner: worker
    group: worker

- name: Add global package directory to PATH
  blockinfile:
    path: /home/worker/.bashrc
    insertbefore: BOF
    block: |
      # global npm packages

      NPM_PACKAGES="${HOME}/.npm-packages"
      export PATH="$NPM_PACKAGES/bin:$PATH"
      # Unset manpath so we can inherit from /etc/manpath via the `manpath` command
      unset MANPATH # delete if you already modified MANPATH elsewhere in your config
      export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"
